table _Measures
	lineageTag: 84ecbe50-aacc-4993-aadb-39a684e25dec

	measure 'Total Sacos Exportados' = SUM(ExportatorsDest[Sacos de 60 Kg. Exportados])
		formatString: #,0
		displayFolder: Exporters
		lineageTag: bb29b462-c87b-4395-a9a5-619979d8a8e9

	measure 'Valor Total Exportado (USD)' = SUM(ExportatorsDest[Valor Factura (USD)*])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Exporters
		lineageTag: 533451fc-7fb0-4755-9fd3-0a3ecf030d37

	measure 'Porcentaje de Incremento por Mes' =
			
			VAR current_date=SELECTEDVALUE(ExportatorsDest[Date_id])
			VAR previous_date=IF(SELECTEDVALUE(DimDate[Month Number])>1, DATE(SELECTEDVALUE(DimDate[Year]), SELECTEDVALUE(DimDate[Month Number])-1, SELECTEDVALUE(DimDate[Day])), DATE(SELECTEDVALUE(DimDate[Year])-1, 12, SELECTEDVALUE(DimDate[Day])))
			VAR current_value=CALCULATE([Valor Total Exportado (USD)], DimDate[Date_id]=current_date)
			VAR previous_value=CALCULATE([Valor Total Exportado (USD)], DimDate[Date_id]=previous_date)
			VAR result=DIVIDE(current_value-previous_value, previous_value, 0)
			RETURN
			result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Exporters
		lineageTag: a6504210-e9b5-4007-86ac-bb0c01018c43

	measure 'Sacos de 60 kg Recibidos' = SUM(DestinationsVolume[Sacos (60 kg)])
		formatString: #,0
		displayFolder: Dest
		lineageTag: 71a6b4b0-57a5-4b66-a881-50ff90b899bb

	measure 'Total Valor Recibido (USD)' = SUM(DestinationsVolume[Valor (USD)])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Dest
		lineageTag: a2e34073-75da-44bd-a902-a150a54a5ec9

	measure 'Tooltip Title' = "Sacos de 60 kg Recibidos - " & SELECTEDVALUE(DimCountry[País])
		displayFolder: Labels
		lineageTag: 28086a4a-cf90-4402-92b8-af0fca72a5f1

	measure 'Sacos de 60 kg Exportados' = SUM(PortsVolume[Sacos de 60 Kg. Exportados])
		formatString: #,0
		displayFolder: Ports
		lineageTag: 46553b0c-7226-450a-9ddc-015edddb62f7

	measure 'Valor Exportado (USD)' = SUM(PortsVolume[Valor provisional de la Exportación (USD) *])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Ports
		lineageTag: 0670cbc4-b6d7-48a6-a467-3eccf7bd1158

	measure 'Ports Card Title' = "Resultados " & IF(MIN(DimDate[Year])=MAX(DimDate[Year]), MIN(DimDate[Year]), MIN(DimDate[Year]) & " - " & MAX(DimDate[Year]))
		displayFolder: Ports
		lineageTag: 13275cd0-22f9-4b26-b8da-87f0c8b40cee

	measure 'Mes de Mayor Exportacion' = CALCULATE(FIRSTNONBLANK(_SUMALLDATESPORTS[Date_id], 1), FILTER(_SUMALLDATESPORTS, _SUMALLDATESPORTS[Suma Puertos]=MAX(_SUMALLDATESPORTS[Suma Puertos])))
		formatString: yyyy-mm
		displayFolder: Ports
		lineageTag: 05d4cd89-5e17-4e20-b061-0106f473d81c

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Mes de Menor Exportación' = CALCULATE(FIRSTNONBLANK(_SUMALLDATESPORTS[Date_id], 1), FILTER(_SUMALLDATESPORTS, _SUMALLDATESPORTS[Suma Puertos]=MIN(_SUMALLDATESPORTS[Suma Puertos])))
		formatString: yyyy-mm
		displayFolder: Ports
		lineageTag: 61a384dd-74e5-441f-aafb-d9b75727a946

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Mayor Puerto' = CALCULATE(FIRSTNONBLANK(_SUMALLPORTS[Port], 1), FILTER(_SUMALLPORTS, _SUMALLPORTS[Suma Puertos]=MAX(_SUMALLPORTS[Suma Puertos])))
		displayFolder: Ports
		lineageTag: 982983aa-fcba-4e09-8014-f656ea5d3260

	measure 'Menor Puerto' = CALCULATE(FIRSTNONBLANK(_SUMALLPORTS[Port], 1), FILTER(_SUMALLPORTS, _SUMALLPORTS[Suma Puertos]=MIN(_SUMALLPORTS[Suma Puertos])))
		displayFolder: Ports
		lineageTag: 2a3d2df1-95b7-4476-83bc-6419fabc540a

	measure 'Total Sacos Exportados Max' = MAX(_SUMALLPORTS[Suma Puertos])
		formatString: 0
		displayFolder: Ports
		lineageTag: 6dcda91e-f18c-42ce-b36a-a88b09e3a5bf

	measure 'Total Sacos Exportados Min' = MIN(_SUMALLPORTS[Suma Puertos])
		formatString: 0
		displayFolder: Ports
		lineageTag: b33af49c-cfb5-483b-a011-28fcbab837d5

	measure 'Main Graph Title Exportadores' = "Exportaciones de Café (" & IF(MIN(DimDate[Year])=MAX(DimDate[Year]), SELECTEDVALUE(DimDate[Year]), MIN(DimDate[Year]) & " - " & MAX(DimDate[Year])) & ")"
		displayFolder: Labels
		lineageTag: b240772a-5b36-4c74-bf5d-de1c0d4fe802

	measure 'Sacos de Cafe Verde' = CALCULATE([Sacos de 60 kg Recibidos], DimTypes[Coffee Type]="Café Verde")
		formatString: 0
		displayFolder: Dest
		lineageTag: f4a2f8a6-7a75-4a51-b40a-8ea269122419

	measure 'Sacos de Cafe Soluble' = CALCULATE([Sacos de 60 kg Recibidos], DimTypes[Coffee Type]="Soluble")
		formatString: 0
		displayFolder: Dest
		lineageTag: 14882940-c640-42ff-8e8f-70a0be5505d5

	measure 'Mejor Fecha Puerto' = CALCULATE(FIRSTNONBLANK('GroupByTable Ports'[DimDate_Date_id], 1), FILTER('GroupByTable Ports', 'GroupByTable Ports'[TotalperYear]=MAX('GroupByTable Ports'[TotalperYear])))
		formatString: mmmm yyyy
		lineageTag: 7c1dfef5-3827-46f6-9c8c-eadd99f7930b

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Sacos Totales Sin Filtros' = CALCULATE([Sacos de 60 kg Recibidos], REMOVEFILTERS(DimCountry))
		formatString: 0
		displayFolder: Dest
		lineageTag: 6c9f9dea-58e9-4adb-a384-1acb02237d73

	measure 'Porcentaje de Sacos Pais' = DIVIDE([Sacos de 60 kg Recibidos], [Sacos Totales Sin Filtros], 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Dest
		lineageTag: 61771b79-90f8-4e62-857f-a2313eb8f879

	measure 'Porcentaje de Incremento Sacos Puertos' =
			
			VAR ano_actual=SELECTEDVALUE(DimDate[Year])
			VAR ano_anterior=ano_actual-1
			VAR sacos_actuales=CALCULATE([Sacos de 60 kg Exportados], DimDate[Year]=ano_actual)
			VAR sacos_anterior=CALCULATE([Sacos de 60 kg Exportados], DimDate[Year]=ano_anterior)
			VAR resultado=DIVIDE(sacos_actuales-sacos_anterior, sacos_anterior)
			RETURN
			resultado
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ports
		lineageTag: 5a15fbcb-a78e-4d28-adec-ebb072c907e7

	measure 'Porcentaje de Exportaciones Puerto' = DIVIDE([Sacos de 60 kg Exportados], CALCULATE([Sacos de 60 kg Exportados], REMOVEFILTERS()), 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c08a7ccb-8cd8-4dbc-8537-316ffe785935

	measure 'Sacos de 60 kg Exportados Sin Filtros' = CALCULATE([Sacos de 60 kg Exportados], REMOVEFILTERS())
		formatString: 0
		lineageTag: c52e8c6b-1038-4f65-9379-a70e66677ee8

	measure 'Promedio de Precio de Café por Carga' = AVERAGE(PortsVolume[Valor por Carga])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 39f0c9af-4ed1-409f-b06b-96c9ecab4b63

	measure 'Tooltip Precio Label' = "Precio Promedio por Carga (" & SELECTEDVALUE(DimTypes[Coffee Type]) & ")"
		displayFolder: Labels
		lineageTag: bc269fd5-b31a-4e8d-b78f-c472d96a10ba

	column -
		dataType: string
		isHidden
		lineageTag: 75dcb3ea-4bc3-40ce-851b-3cf04139443f
		summarizeBy: none
		sourceColumn: -

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"-" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"-", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

