table _Measures
	lineageTag: 84ecbe50-aacc-4993-aadb-39a684e25dec

	measure 'Total Sacos Exportados' = SUM(ExportatorsDest[Sacos de 60 Kg. Exportados])
		formatString: 0
		displayFolder: Exporters
		lineageTag: bb29b462-c87b-4395-a9a5-619979d8a8e9

	measure 'Valor Total Exportado (USD)' = SUM(ExportatorsDest[Valor Factura (USD)*])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Exporters
		lineageTag: 533451fc-7fb0-4755-9fd3-0a3ecf030d37

	measure 'Porcentaje de Incremento por Mes' =
			
			VAR current_date=SELECTEDVALUE(ExportatorsDest[Date_id])
			VAR previous_date=month
			VAR current_value=CALCULATE([Valor Total Exportado (USD)], ExportatorsDest[Date_id]=current_date)
			VAR previous_value=CALCULATE([Valor Total Exportado (USD)], ExportatorsDest[Date_id]=previous_date)
			VAR result=DIVIDE(current_value-previous_value, previous_value, 0)
			RETURN
			result
		displayFolder: Exporters
		lineageTag: a6504210-e9b5-4007-86ac-bb0c01018c43

	measure 'Sacos de 60 kg Recibidos' = SUM(DestinationsVolume[Sacos (60 kg)])
		formatString: #,0
		displayFolder: Dest
		lineageTag: 71a6b4b0-57a5-4b66-a881-50ff90b899bb

	measure 'Total Valor Recibido (USD)' = SUM(DestinationsVolume[Valor (USD)])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Dest
		lineageTag: a2e34073-75da-44bd-a902-a150a54a5ec9

	measure 'Tooltip Title' = "Sacos de 60 kg Recibidos - " & SELECTEDVALUE(DimCountry[Country])
		displayFolder: Labels
		lineageTag: 28086a4a-cf90-4402-92b8-af0fca72a5f1

	column -
		dataType: string
		lineageTag: 75dcb3ea-4bc3-40ce-851b-3cf04139443f
		summarizeBy: none
		sourceColumn: -

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"-" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"-", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

