table DimPorts
	lineageTag: 19659f0b-e874-4a10-ada8-cdf901637f2d

	column Port_id
		dataType: int64
		formatString: 0
		lineageTag: ef67f38c-e08c-48d6-9c80-c43bfc816a1a
		summarizeBy: none
		sourceColumn: Port_id

		annotation SummarizationSetBy = Automatic

	column Port
		dataType: string
		lineageTag: 980068d4-5fa3-4014-bd87-70260d3decb6
		summarizeBy: none
		sourceColumn: Port

		annotation SummarizationSetBy = Automatic

	column Latitud
		dataType: double
		lineageTag: 233182c4-c991-42af-a10d-beb7c155ea77
		summarizeBy: sum
		sourceColumn: Latitud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitud
		dataType: double
		lineageTag: 4bc89ad3-ede5-45a0-b214-885663b4163b
		summarizeBy: sum
		sourceColumn: Longitud

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimPorts = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Santiago\OneDrive\Courses\PowerBICourse\ColombianCoffee\ExportacionesSource.xlsx"), null, true),
				    Port_Type_Vol_Sheet = Source{[Item="Port_Type_Vol",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Port_Type_Vol_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Año", Int64.Type}, {"Mes", Int64.Type}, {"Puerto de embarque", type text}, {"Tipo de café", type text}, {"Sacos de 70 kg. equivalente real Exportados", Int64.Type}, {"Sacos de 60 Kg. Exportados", Int64.Type}, {"Valor provisional de la Exportación (USD) *", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Sacos de 70 kg. equivalente real Exportados"}),
				    #"Puerto de embarque1" = #"Removed Columns"[Puerto de embarque],
				    #"Converted to Table" = Table.FromList(#"Puerto de embarque1", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Removed Duplicates" = Table.Distinct(#"Converted to Table"),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"Column1", "Port"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index",{{"Index", "Port_id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Port_id", "Port"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Port", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Aerp.","Aeropuerto",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Aeropuerto José M.Cordoba","Aeropuerto José María Cordoba, Medellín",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Aeropuerto José María Cordoba, Medellín","Aeropuerto Internacional José María Córdova",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Aeropuerto Internacional José María Córdova","Aeropuerto Internacional José María Córdova, Colombia",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Aeropuerto Internacional José María Córdova, Rionegro","",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Aeropuerto Internacional José María Córdova, Colombia","Aeropuerto Internacional José María Córdova, Rionegro",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","AeropuertoAlfonso Bonilla","Aeropuerto Alfonso Bonilla",Replacer.ReplaceText,{"Port"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Aeropuerto Internacional José María Córdova, Rionegro","Aeropuerto José María Córdova",Replacer.ReplaceText,{"Port"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value7", {"Port_id"}, #"source-port-location", {"Port_id"}, "source-port-location", JoinKind.LeftOuter),
				    #"Expanded source-port-location" = Table.ExpandTableColumn(#"Merged Queries", "source-port-location", {"Latitud", "Longitud"}, {"Latitud", "Longitud"})
				in
				    #"Expanded source-port-location"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

