table DimTypes
	lineageTag: 55a8d142-3d84-48a3-a1ad-7608971a3480

	column Type_id
		dataType: int64
		formatString: 0
		lineageTag: b85dc34f-7c06-40c2-907c-291e377a15ab
		summarizeBy: none
		sourceColumn: Type_id

		annotation SummarizationSetBy = Automatic

	column 'Coffee Type'
		dataType: string
		lineageTag: 68b77fb8-e8ad-4e19-8d0f-b1d0b11e8626
		summarizeBy: none
		sourceColumn: Coffee Type

		annotation SummarizationSetBy = Automatic

	partition DimTypes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Santiago\OneDrive\Courses\PowerBICourse\ColombianCoffee\ExportacionesSource.xlsx"), null, true),
				    Dest_Vol_Type_Sheet = Source{[Item="Dest_Vol_Type",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dest_Vol_Type_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Año", Int64.Type}, {"Mes", Int64.Type}, {"País de destino", type text}, {"Tipo de café", type text}, {"Sacos de 70 kg. equivalente real Exportados", Int64.Type}, {"Sacos de 60 Kg. Exportados", Int64.Type}, {"Valor provisional de la Exportación (USD) *", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Sacos de 70 kg. equivalente real Exportados"}),
				    #"Tipo de café1" = #"Removed Columns"[Tipo de café],
				    #"Converted to Table" = Table.FromList(#"Tipo de café1", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Appended Query" = Table.Combine({#"Converted to Table", #"Tipo de café"}),
				    #"Removed Duplicates" = Table.Distinct(#"Appended Query"),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"Column1", "Type"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index",{{"Index", "Type_id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Type_id", "Type"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns",{{"Type", "Coffee Type"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

